/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GenerateIndexRouteImport } from './routes/generate/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as CertIndexRouteImport } from './routes/cert/index'
import { Route as AuditIndexRouteImport } from './routes/audit/index'
import { Route as CertUidRouteImport } from './routes/cert/$uid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateIndexRoute = GenerateIndexRouteImport.update({
  id: '/generate/',
  path: '/generate/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const CertIndexRoute = CertIndexRouteImport.update({
  id: '/cert/',
  path: '/cert/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditIndexRoute = AuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => rootRouteImport,
} as any)
const CertUidRoute = CertUidRouteImport.update({
  id: '/cert/$uid',
  path: '/cert/$uid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cert/$uid': typeof CertUidRoute
  '/audit': typeof AuditIndexRoute
  '/cert': typeof CertIndexRoute
  '/chat': typeof ChatIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/generate': typeof GenerateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cert/$uid': typeof CertUidRoute
  '/audit': typeof AuditIndexRoute
  '/cert': typeof CertIndexRoute
  '/chat': typeof ChatIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/generate': typeof GenerateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cert/$uid': typeof CertUidRoute
  '/audit/': typeof AuditIndexRoute
  '/cert/': typeof CertIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/generate/': typeof GenerateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cert/$uid'
    | '/audit'
    | '/cert'
    | '/chat'
    | '/dashboard'
    | '/generate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cert/$uid'
    | '/audit'
    | '/cert'
    | '/chat'
    | '/dashboard'
    | '/generate'
  id:
    | '__root__'
    | '/'
    | '/cert/$uid'
    | '/audit/'
    | '/cert/'
    | '/chat/'
    | '/dashboard/'
    | '/generate/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CertUidRoute: typeof CertUidRoute
  AuditIndexRoute: typeof AuditIndexRoute
  CertIndexRoute: typeof CertIndexRoute
  ChatIndexRoute: typeof ChatIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  GenerateIndexRoute: typeof GenerateIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate/': {
      id: '/generate/'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cert/': {
      id: '/cert/'
      path: '/cert'
      fullPath: '/cert'
      preLoaderRoute: typeof CertIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit/': {
      id: '/audit/'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cert/$uid': {
      id: '/cert/$uid'
      path: '/cert/$uid'
      fullPath: '/cert/$uid'
      preLoaderRoute: typeof CertUidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CertUidRoute: CertUidRoute,
  AuditIndexRoute: AuditIndexRoute,
  CertIndexRoute: CertIndexRoute,
  ChatIndexRoute: ChatIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  GenerateIndexRoute: GenerateIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
