import { useEffect, useRef, useState } from 'react'
import { Check, Copy } from 'lucide-react'
import { cnm } from '@/utils/style'

interface CodeSnippetProps {
  code: string
  language?: string
  filename?: string
}

/**
 * Syntax-highlighted code block via Shiki (lazy-loaded on first render).
 *
 * Security: Shiki escapes all HTML inside code — we set innerHTML only on the
 * Shiki-produced output. The `code` prop is user-supplied Solidity text;
 * Shiki never evals it, it only tokenises. This is the ONLY place in the app
 * where dangerouslySetInnerHTML is permitted (ADR-006).
 */
export default function CodeSnippet({
  code,
  language = 'solidity',
  filename,
}: CodeSnippetProps) {
  const [html, setHtml] = useState<string | null>(null)
  const [copied, setCopied] = useState(false)
  const copyTimer = useRef<ReturnType<typeof setTimeout> | null>(null)

  useEffect(() => {
    let cancelled = false

    async function highlight() {
      const { codeToHtml } = await import('shiki')
      const result = await codeToHtml(code, {
        lang: language,
        theme: 'github-dark',
      })
      if (!cancelled) setHtml(result)
    }

    void highlight()
    return () => {
      cancelled = true
    }
  }, [code, language])

  // Cleanup copy timer on unmount
  useEffect(() => {
    return () => {
      if (copyTimer.current) clearTimeout(copyTimer.current)
    }
  }, [])

  function handleCopy() {
    void navigator.clipboard.writeText(code).then(() => {
      setCopied(true)
      copyTimer.current = setTimeout(() => setCopied(false), 1500)
    })
  }

  return (
    <div className="overflow-hidden rounded-[8px] border border-[rgba(255,255,255,0.08)]">
      {/* Header bar */}
      <div className="flex items-center justify-between border-b border-[rgba(255,255,255,0.08)] bg-[#191a1b] px-4 py-2">
        <span className="text-[12px] leading-[1.4] tracking-[-0.13px] text-[#8a8f98]">
          {filename ?? language}
        </span>
        <button
          onClick={handleCopy}
          aria-label={copied ? 'Copied' : 'Copy code'}
          className={cnm(
            'flex items-center gap-1.5 rounded-md px-2 py-1 text-[12px] transition-colors',
            copied
              ? 'text-[#10b981]'
              : 'text-[#62666d] hover:bg-[rgba(255,255,255,0.04)] hover:text-[#d0d6e0]',
          )}
        >
          {copied ? <Check className="h-3.5 w-3.5" /> : <Copy className="h-3.5 w-3.5" />}
          {copied ? 'Copied' : 'Copy'}
        </button>
      </div>

      {/* Code body */}
      <div className="overflow-x-auto bg-[#0d1117] p-4 text-[14px] leading-[1.5] font-mono">
        {html != null ? (
          // Shiki output — HTML is generated by Shiki's tokeniser, not from user input.
          // dangerouslySetInnerHTML is intentional here (ADR-006): Shiki escapes all code content.
          <div dangerouslySetInnerHTML={{ __html: html }} className="[&_pre]:!bg-transparent [&_pre]:!p-0" />
        ) : (
          <pre className="whitespace-pre-wrap text-[#8a8f98]">
            <code>{code}</code>
          </pre>
        )}
      </div>
    </div>
  )
}
